# ====================================================================
# CONFIG MASTER TEMPLATE PARA PROJETOS DE CLASSIFICAÇÃO (Scikit-learn)
# ====================================================================


# --- CONFIGURAÇÃO GERAL DA RUN ---
experiment_name: "Classificação Iris"
run_name: "RandomForest_experimento_1"
trainer_type: "generic_classification"

# --- FONTES DE DADOS ---
data:
  path: "iris_data.csv"
  target_column: "target"

# --- PARÂMETROS ---
params:
  model_name: "RandomForestClassifier" 
  dataset_name: "Scikit-learn Iris" 
  seed: 2024 

  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  criterion: "gini"

# --- MÉTRICAS E ARTEFATOS DE SAÍDA ---
metrics_to_log:
  Precision 
  Recall 
  F1-Score 
  Top-1 Accuracy 
  Top-5 Accuracy 
  ROC-AUC 

output_artifacts_to_log:
  Confusion matrix: "confusion_matrix.png"
  ROC / PR Curves: "roc_curve.png" 